### ISSUE TITLE
Don't add remarks sections to enum fields

### ISSUE THREAD

**Issue by gewarren** [carlossanlop/DocsPortingTool#24]
Remarks for enum fields are invalid (there's nowhere to display them in docs and they now cause a build warning). Please update the tool to not add empty remarks nodes for enum fields.

**Comment by carlossanlop** [comment]
@gewarren do you know why Enum fields do not show remarks? I can fix the tool, it's no problem, but maybe we should request this feature to the Docs dev team.

**Comment by gewarren** [comment]
@tannergooding would also like a way to show enum remarks (and applicable versions). So it is probably worth opening a request. See https://github.com/dotnet/dotnet-api-docs/pull/5201#issuecomment-788214406.

**Comment by gewarren** [comment]
Here's the internal work item regarding enum fields having their own pages in API docs: https://ceapex.visualstudio.com/Engineering/_workitems/edit/390259

**Comment by gewarren** [comment]
Closing this issue since it will be fixed on the docs side.
