### ISSUE TITLE
DocsPortingTool fails to convert generic targets of `<see cref` correctly

### ISSUE THREAD

**Issue by ericstj** [carlossanlop/DocsPortingTool#41]
The following line: https://github.com/dotnet/dotnet-api-docs/blob/96b853d5e314fc00f8fa2acad402ddb3a00b76a7/xml/System.IO.Pipelines/PipeOptions.xml#L160

```
<summary>Gets the <see cref="T:System.Buffers.MemoryPool`1" /> object used for buffer management.</summary>
```

When ported did not change the syntax of the generic type.  CSC then complains:

```
error CS1584: XML comment has syntactically incorrect cref attribute 'System.Buffers.MemoryPool`1' 
```

To fix it I had to manually change the generic parameter syntax to `{T}`.  Hope I got it right?

The tool should be able to do this for me.

Command:
```
-Direction ToTripleSlash -CsProj c:\src\dotnet\runtime\src\libraries\System.IO.Pipelines\src\System.IO.Pipelines.csproj -docs c:\src\dotnet\dotnet-api-docs\xml -IncludedAssemblies System.IO.Pipelines -IncludedNamespaces System.IO
```

Using dotnet/runtime add68df26af8c0dab2afb13da1f0ca033753fd0b

There were a mess of these issues in this project.  I ended up find->replacing `` `1`` with `{T}` to deal with them.  I checked and the resultant XML was correct.  Not sure if that's a great strategy, ideally the *actual* type parameter name could be used.

**Comment by carlossanlop** [comment]
Ah good point, thanks for sharing @ericstj. `` `1 `` is valid in dotnet-api-docs, but not in triple slash. I'll work on this.
